on: [push]

jobs:
  storybook_indexing_n_cleanup_job:
    runs-on: ubuntu-latest
    name: Cleanup merged PRs and update Storybook index
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build
        run: | # Install the packages
          npm install
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            r:
              - 'r/**'
      - name: storybook versions update
        uses: ./ # Uses an action in the root directory
        id: storybook_versions
        with: 
          isRelease: ${{ steps.filter.outputs.r }} #
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update storybook versions ${{ steps.storybook_versions.outputs.version }}'
          add: "['storybooks.json', 'pr/**']"